enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[AdobeLightroom]
enabled = true
version = "8.2.3"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"

[Backdrops]
enabled = true
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/backdrops/backdrops-wallpapers/"
#uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[Bandcamp]
enabled = true
#apkmirror-dlurl = "https://www.apkmirror.com/apk/bandcamp-inc/bandcamp/"
uptodown-dlurl = "https://bandcamp.en.uptodown.com/android"

[Duolingo]
enabled = true
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo/"
#uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
included-patches = "'Disable ads'"
exclusive-patches = true

[Facebook]
enabled = true
#arch = "arm-v7a"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"

[Instagram]
enabled = true
arch = "arm-v7a"
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
#uptodown-dlurl = "https://instagram.en.uptodown.com/android"

[Messenger]
enabled = true
#arch = "arm-v7a"
#apkmirror-dpi = "360-480dpi"
#apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"

[Music]
enabled = true
arch = "arm-v7a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
#uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Pixiv]
enabled = true
#apkmirror-dlurl = "https://www.apkmirror.com/apk/pixiv-inc/pixiv/"
uptodown-dlurl = "https://pixiv.en.uptodown.com/android"

[Reddit]
enabled = true
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
#uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[SoundCloud]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud/"
#uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"

[TikTok]
enabled = true
#apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"

[Tumblr]
enabled = true
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tumblr-inc/tumblr/"
#uptodown-dlurl = "https://twitch.en.uptodown.com/android"

[Twitter]
enabled = true
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
#uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[YouTube]
enabled = true
#apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
